# checkout.yaml
name: checkout feature test

on:
  push:
    branches:
      - main

jobs:
  external-repo-checkout: 
    runs-on: ubuntu-latest

    # Workflowが存在するメインリポジトリをチェックアウト
    steps:
      - name: Checkout my repository
        uses: actions/checkout@v4

      # 他のリポジトリをチェックアウトする
      - name: Checkout external repository Hello-world
        uses: actions/checkout@v4
        with:
          repository: 'octocat/Hello-World' # リモートリポジトリのパス
          path: 'hello_world' #./hello_worldの中に保存される
          
      - name: Checkout external repository Gitignore
        uses: actions/checkout@v4
        with:
          repository: github/gitignore
          path: 'gitignore'


      # 動作確認
      - name: Verify Checkout
        shell: bash
        run: |
          echo "Current Dir Containing Folders:"
          ls -F
          echo "Check external repository: octocat/Hello-World"
          ls -F ./hello_world
          echo "Check external repository: github/gitignore"
          ls -F ./gitignore