name: Git push Test

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  push-job: 
    runs-on: ubuntu-latest

    steps:
      - name: Setup - Checkout repository
        uses: actions/checkout@v4

      - name: Setup - Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
          check-latest: false

      - name: execute script
        run: python ./test_script/push_script.py
      
      - name: github push
        # pushを目指していて無限ループされるので、[skip ci]を追加
        run: |
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git config --global user.name "github-actions[bot]"
         git status
         git add .
         git commit -m "add: add test file. It should not activate a new workflow executing."
         git push origin main 